trigger:
- master

pr:
- master

pool:
  vmImage: internal-macos-10.15

variables:
  Configuration: Release
  SDK:

  # Xcode 11.3.1 version is the last one that has compatible bitcode with Xcode 11.0 (minimal supported).
  XCODE_PATH: '/Applications/Xcode_11.3.1.app/Contents/Developer'

jobs:
- job:
  displayName: Build SDK for All Platforms
  steps:
  - checkout: self

  - bash: 'brew install doxygen graphviz protobuf-c'
    displayName: 'Install dependencies'

  - task: Xcode@5
    displayName: 'Build Crash Reporter'
    inputs:
      xcWorkspacePath: CrashReporter.xcodeproj
      scheme: 'CrashReporter'
      xcodeVersion: specifyPath
      xcodeDeveloperDir: '$(XCODE_PATH)'
      args: 'SYMROOT="$(Build.BinariesDirectory)"'

  - task: Xcode@5
    displayName: 'Build CrashReporter macOS Framework for Apple Silicon'
    inputs:
      xcWorkspacePath: CrashReporter.xcodeproj
      scheme: CrashReporter macOS Framework
      xcodeVersion: specifyPath
      xcodeDeveloperDir: '/Applications/Xcode_12.2.app/Contents/Developer'
      args: 'SYMROOT="$(Build.BinariesDirectory)"'

  - template: build-apple-silicon-template.yml
    parameters:
      scheme: 'plcrashutil'

  - bash: |
      cp -f "Release-macosx/libCrashReporter.a" "Release/Static/libCrashReporter-MacOSX-Static.a"
      cp -Rf "Release-macosx/CrashReporter.framework" "Release-macosx/CrashReporter.framework.dSYM" "Release"
      cp -f "Release-macosx/plcrashutil" "Release"
    displayName: 'Combine Binaries'
    workingDirectory: '$(Build.BinariesDirectory)'

  - bash: |
      VERSION="$(cd $BUILD_SOURCESDIRECTORY && agvtool vers -terse)"
      "$BUILD_SOURCESDIRECTORY/Scripts/create-archive.sh" "CrashReporter-$VERSION" "iOS Framework" "tvOS Framework" "Mac OS X Framework" "Tools"
      "$BUILD_SOURCESDIRECTORY/Scripts/create-archive.sh" "CrashReporter-Static-$VERSION" Static/*
      "$BUILD_SOURCESDIRECTORY/Scripts/create-archive.sh" "CrashReporter-XCFramework-$VERSION" "CrashReporter.xcframework"
    displayName: 'Create Archives'
    workingDirectory: '$(Build.BinariesDirectory)/Release'

  - task: CopyFiles@2
    displayName: 'Copy Archives to Staging Directory'
    inputs:
      SourceFolder: '$(Build.BinariesDirectory)/Release'
      Contents: '*.zip'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      ArtifactName: Release

- template: analyze-and-test-template.yml
  parameters:
    platforms: [iOS, macOS, tvOS, MacCatalyst ]
