trigger:
- master

pr:
- master

pool:
  vmImage: internal-macos-10.15

variables:
  Configuration: Release
  SDK:

  # Xcode 11.3.1 version is the last one that has compatible bitcode with Xcode 11.0 (minimal supported).
  XCODE_PATH: '/Applications/Xcode_11.3.1.app/Contents/Developer'

jobs:
- template: analyze-and-test-template.yml
  parameters:
    platforms: [iOS, macOS, tvOS, MacCatalyst ]
