parameters:
- name: xcframeworkName
  type: string

- name: outputPath
  type: string
  default: ""

steps:
- bash: |
    cp -f "Release-macosx/libCrashReporter.a" "Release/Static/libCrashReporter-MacOSX-Static.a"
    lipo -info "Release/Static/libCrashReporter-MacOSX-Static.a"
    rm -rf "Release/Mac OS X Framework/CrashReporter.framework" "Release/Mac OS X Framework/CrashReporter.framework.dSYM"
    cp -R "Release-macosx/CrashReporter.framework" "Release-macosx/CrashReporter.framework.dSYM" "Release/Mac OS X Framework"
    lipo -info "Release/Mac OS X Framework/CrashReporter.framework/CrashReporter"
    cp -f "Release-macosx/plcrashutil" "Release/Tools"
    lipo -info "Release/Tools/plcrashutil"

    rm -rf "Release-xcframework/{{ parameters.xcframeworkName }}/macos-x86_64/CrashReporter.framework"
    cp -R "Release-macosx/CrashReporter.framework" "Release-xcframework/{{ parameters.xcframeworkName }}/macos-x86_64"
    lipo "Release-xcframework/{{ parameters.xcframeworkName }}/ios-i386_x86_64-simulator/CrashReporter.framework/CrashReporter" \
      "Release-iphonesimulator/CrashReporter.framework/CrashReporter" \
      -create -output "Release-xcframework/{{ parameters.xcframeworkName }}/ios-i386_x86_64-simulator/CrashReporter.framework/CrashReporter" || exit 1
    lipo "Release-xcframework/{{ parameters.xcframeworkName }}/ios-x86_64-maccatalyst/CrashReporter.framework/Versions/A/CrashReporter" \
      "Release-maccatalyst/CrashReporter.framework/Versions/A/CrashReporter" \
      -create -output "Release-xcframework/{{ parameters.xcframeworkName }}/ios-x86_64-maccatalyst/CrashReporter.framework/Versions/A/CrashReporter" || exit 1
    lipo "Release-xcframework/{{ parameters.xcframeworkName }}/tvos-x86_64-simulator/CrashReporter.framework/CrashReporter" \
      "Release-appletvsimulator/CrashReporter.framework/CrashReporter" \
      -create -output "Release-xcframework/{{ parameters.xcframeworkName }}/tvos-x86_64-simulator/CrashReporter.framework/CrashReporter" || exit 1

    rm -rf "Release/{{ parameters.xcframeworkName }}"
    for framework in Release-xcframework/{{ parameters.xcframeworkName }}/*/CrashReporter.framework; do
      xcframeworks+=( -framework "$framework")
    done
    xcodebuild -create-xcframework "${xcframeworks[@]}" -output "Release/{{ parameters.outputPath }}"
    ls "Release/{{ parameters.outputPath }}"
  displayName: 'Combine Binaries'
  workingDirectory: '$(Build.BinariesDirectory)'
